---
layout: cv
title: Ian's CV
---

## Currently

Pursuing a BS in Accounting at Brigham Young University - Idaho, graduating December 2026.

### Specialized in

Tax return preparation, financial accounting, income taxation, data analytics, spreadsheet modeling

### Skills

Communication skills, Organizational skills, Attention to detail

Technical Skills: CCH Axcess, Excel, Power BI, SQL, Python

## Education

`December 2026`
__Brigham Young University - Idaho__, Rexburg, ID

- BS, Accounting
- GPA: 3.96
- Relevant coursework: financial accounting, managerial accounting, cost accounting, income taxation, business statistics, spreadsheet application

## Experience

`January 2026 - April 2026`
__Tax Intern__, Eide Bailly LLP, Boise, ID

- Prepared and reviewed nearly 100 partnership and individual tax returns using CCH Axcess, ensuring accuracy and compliance with federal and state filing requirements
- Collaborated with a team of tax associates across multiple client engagements, coordinating workpapers and supporting documentation in CCH Axcess to meet filing deadlines
- Adapted to a high-volume, deadline-driven environment during peak season, prioritizing client deliverables to ensure on-time filing

`May 2025 - August 2025`
__Sales Representative__, Fox Pest Control, Manchester, NH

- Generated over $55,000 in service revenue by accurately managing more than 60 customer records and service agreements
- Delivered consistent customer satisfaction by quickly adapting to new locations and demographics and maintaining high-quality interactions in a fast-paced, high-volume environment

`January 2025 - April 2025`
__Sales Support Representative__, Safestreets Security, Rexburg, ID

- Performed timely credit checks on potential customers to ensure risk compliance
- Acted as primary support contact for sales representatives, resolving issues related to scheduling, installation, and equipment orders

`June 2022 - June 2024`
__Volunteer Representative__, LDS Church, Eastern Visayas, Philippines

- Acquired fluency in Cebuano and Waray Waray
- Developed professional interpersonal skills by working with people from diverse backgrounds
- Enlarged leadership abilities by training and leading 20 other representatives

`June 2020 - May 2022`
__Shift Lead__, Chick-fil-A, Ammon, ID

- Demonstrated exceptional communication skills while interacting with customers and working with coworkers in a team environment
- Directed and coached 20-30 team members throughout a shift to maintain high operational standards and service speed
- Increased overall efficiency and sales by identifying and resolving bottlenecks during peak hours

<!-- ### Footer

Last updated: July 2026 -->